### ISSUE TITLE
Generering av D-nummer

### ISSUE THREAD

**Issue by petteas** [navikt/nav-faker#11]
Hei!
Ser at dere lager d-Nummer på følgende måte:
```
public dnummer(fødselsdato?: Date, kjønn?: number): string {
       const fødselsnummer = this.generer(fødselsdato, kjønn);

       const førsteSiffer = Number(fødselsnummer.charAt(0));
       const nyttFørstesiffer = førsteSiffer + 4;

       return String(nyttFørstesiffer).concat(fødselsnummer.substring(1));
   }
```
Blir ikke kontrollsifferene feil her? Kunne det være en ide å sende inn isDnummer av type bool til generer-funksjonen og plusse på 4 på førstesifferet før man regner ut kontrollsifferene?

PS: Superbra at dere lager dette. Ønsker støtte for DUF-Nummer også!

![bitmoji](https://render.bitstrips.com/v2/cpanel/60065a1d-f894-4f37-b480-3609c4cd8b5b-a4ec583e-8459-4e9f-b620-9a26ae2071f2-v1.png?transparent=1&palette=1&width=246)

**Comment by Quist** [comment]
Det har du helt rett i. Skal få fikset det 🌮

**Comment by Quist** [comment]
Lagde #21 for å støtte duf-nummere, @petteas
