### ISSUE TITLE
Automatisk publisering til npm

### ISSUE THREAD

**Issue by Quist** [navikt/nav-faker#29]
Såvidt jeg husker er det fremdeles min bruker som brukes for å publisere til npm. Enten må dere sette opp på travis en annen bruker, eller legge til meg som contributer her på github-repoet.

Legg meg gjerne til som contributor. @winsvold  gjorde det, men det ble tatt bort når jeg ble fjernet fra github-organiasjonen til nav-ikt.

**Comment by nutgaard** [comment]
Byttet til github-actions for publisering da teamet bruker det for alle andre prosjekter. Samtidig lagt til meg som npm-contributer slik at publisering kan gjøres fra github-actions.
