### ISSUE TITLE
Bug: Feil i beregning av fødselsdato (årstall)

### ISSUE THREAD

**Issue by LemurP** [navikt/nav-faker#34]
Denne kode-biten passer ikke med spesifikasjonen[1] av personnummer og fødselsår.

Forventet: 54 < year
Faktisk: 56 < year

https://github.com/navikt/nav-faker/blob/b368df2343c11a4bb4144ff8df7576c7a6db7974/lib/personidentifikator/helpers/fodselsdato-beregner.ts#L34-L35

![Spesifikasjon for personnummer](https://user-images.githubusercontent.com/18642937/87644344-4ce8f980-c74c-11ea-9a5d-c3ff4e9c02c0.png)

[1] https://web.archive.org/web/20141006101356/http://www.kith.no/upload/5588/KITH1001-2010_Identifikatorer-for-personer_v1.pdf

**Comment by nutgaard** [comment]
aha. nice catch. 

Endringen er publisert i v3.2.2
